name: Generar APK de Produccion

# Controla cuándo se ejecutará el flujo de trabajo (de forma manual desde la pestaña Actions)
on:
  workflow_dispatch:

jobs:
  build:
    # Se ejecuta sobre la última versión estable de Ubuntu disponible en GitHub
    runs-on: ubuntu-latest

    steps:
      # 1. Trae el código del repositorio (Actualizado a v4 para corregir advertencia de Node.js)
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2. Configura el entorno de Java (Actualizado a v6 para corregir advertencia de Gradle/Java)
      - name: Configurar JDK de Java
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # 3. Opcional: Da permisos de ejecución al wrapper de Gradle (útil en entornos Linux)
      - name: Otorgar permisos a Gradle Wrapper
        run: chmod +x gradlew

      # 4. Ejecuta la compilación de tu APK utilizando Gradle
      - name: Compilar APK (Build APK)
        run: ./gradlew assembleRelease

      # 5. Sube el APK generado para que lo puedas descargar desde la pestaña de "Artifacts"
      - name: Subir APK como Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: MiApp-Instalable
          path: app/build/outputs/apk/release/app-release-unsigned.apk
